apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-flow-hello-world
spec:
  entrypoint: hello-world
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello ðŸŒŽ"]
---
# Draw a diamond-shaped workflow using Argo Workflows DAG feature
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: draw-diamond
  generateName: draw-diamond-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  # @task: [A, B, C, D]
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      name: echo
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]